/* 
 * Copyright (C) 2015 Anthony Quigel
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jeopardy.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import jeopardy.util.DesktopUtils;
import jeopardy.util.Info;

/**
 * About form, shows program information
 * @author Anthony Quigel
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    private String updateURL = null;

    /**
     * Creates a new About form
     */
    public About() {
        initComponents();
        setLabels();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((screenSize.width / 2) - (getSize().width / 2),
                (screenSize.height / 2) - (getSize().height / 2));
    }

    private void setLabels() {
        labelGame.setText(Info.GAME);
        labelAuthor.setText(Info.AUTHOR);
        labelVersion.setText(Info.VERSION_MAJOR + "."
                + Info.VERSION_MINOR + "." + Info.VERSION_REVISION);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelGameLabel = new javax.swing.JLabel();
        labelAuthorLabel = new javax.swing.JLabel();
        labelVersionLabel = new javax.swing.JLabel();
        labelGame = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");

        labelGameLabel.setText("Game: ");

        labelAuthorLabel.setText("Author: ");

        labelVersionLabel.setText("Version: ");

        labelGame.setText("jLabel4");

        labelAuthor.setText("jLabel5");

        labelVersion.setForeground(new java.awt.Color(0, 51, 204));
        labelVersion.setText("jLabel6");
        labelVersion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelVersion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVersionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelGame))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAuthorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAuthor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelVersionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVersion)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGameLabel)
                    .addComponent(labelGame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAuthorLabel)
                    .addComponent(labelAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVersionLabel)
                    .addComponent(labelVersion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelVersionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVersionMouseClicked
        DesktopUtils.openURL(Info.WEBSITE_URL);
    }//GEN-LAST:event_labelVersionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelAuthorLabel;
    private javax.swing.JLabel labelGame;
    private javax.swing.JLabel labelGameLabel;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JLabel labelVersionLabel;
    // End of variables declaration//GEN-END:variables
}
