/* 
 * Copyright (C) 2015 Anthony Quigel
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jeopardy.gui.lib;

import javax.swing.JTabbedPane;

/**
 * Category form for the GameCreator
 * @author Anthony Quigel
 */
public class CategoryForm extends javax.swing.JPanel {
    
    private int tabIndex = -1;
    private JTabbedPane tabs;

    /**
     * Creates new form CategoryForm
     * 
     * @param tabs reference to the parent JTabbedPane
     * @param tabIndex index of the tab
     */
    public CategoryForm(JTabbedPane tabs, int tabIndex) {
        initComponents();
        this.tabIndex = tabIndex;
        this.tabs = tabs;
        auxInit();
    }
    
    private void auxInit() {
        if (tabs != null) {
            this.textCategory.setText(tabs.getTitleAt(this.tabIndex));
        }
    }
    
    /**
     * Get text of the category
     * @return the category text
     */
    public String getCurrentText() {
        return this.tabs.getTitleAt(this.tabIndex);
    }
    
    /**
     * Get the index of the category tab
     * @return tab index
     */
    public int getTabIndex() {
        return this.tabIndex;
    }
    
    /**
     * Set text of the category
     * @param s text to apply to the category
     */
    public void setText(String s) {
        this.tabs.setTitleAt(tabIndex, s);
        this.textCategory.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCategory = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(150, 40));

        textCategory.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCategoryFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textCategoryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCategoryFocusLost
        this.tabs.setTitleAt(this.tabIndex, this.textCategory.getText());
    }//GEN-LAST:event_textCategoryFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textCategory;
    // End of variables declaration//GEN-END:variables
}
